### ISSUE TITLE
Add new node types for mdx v2

### ISSUE THREAD

**Issue by iAdramelk** [sergioramos/remark-copy-linked-files#105]
[New version of mdx](https://github.com/mdx-js/mdx/issues/1041) (in beta right now) changed jsx parser considerably. Instead of parsing it as one node, it instead creates tree of nodes with its own fields and children. Because of it current version of jsx parsing is not working with the new MDX.

I created fast implementation of the new node types handles. It looks somethings like this:

```js
      mdxBlockElement: async (node) => {
        const selectors = {
          'img': ['src'],
          'source': ['src'],
          'video': ['poster', 'src'],
          'audio': ['src'],
          'param': ['value'],
          'a': ['href'],
        };

        if (Object.keys(selectors).includes(node.name) && node.attributes) {
          for (let attr of node.attributes) {
            if (selectors[node.name].includes(attr.name)) {
              
              const asset = await handleUrl(attr.value);

              assets.push(asset);
              attr.value = asset ? asset.url : attr.value;
            }
          }
        }

        return node;
      },
      mdxSpanElement: (...args) => handlers.mdxBlockElement(...args),
```

It works for my project, but I didn't test it long enough to be sure that it works in all cases. Also it's possible that node syntax for v2 will change before release, so maybe it too early to add these handlers to the library. But in the future something like this will need to be added to the plugin.

**Comment by iAdramelk** [comment]
Works like a charm, thanks!

**Comment by sergioramos** [comment]
@iAdramelk also published a new version with it FYI ;)
