### ISSUE TITLE
`filename` instead of `path` in method signature

### ISSUE THREAD

**Issue by mikenikles** [sergioramos/remark-copy-linked-files#121]
Hi Sérgio,

Thanks for creating this package. I installed it today to use in a [Sapper](https://sapper.svelte.dev/) app with [MDsvex](https://mdsvex.com/docs#remarkplugins--rehypeplugins). MDsvex allows me to provide any Remark plugin which works fine.

I noticed though the `remark-copy-linked-files` plugin didn't work. It turns out, I receive a `filename` rather than a `path` property at https://github.com/sergioramos/remark-copy-linked-files/blob/master/index.js#L44.

If I change that line to the following, it all works as expected:

```js
return async (tree, { cwd, filename: path }) => {
```

I'll continue to look into this, but wondered if you had an idea why that might be the case.

Thanks 🙏

**Comment by sergioramos** [comment]
lmk if the latest version works ;)
