### ISSUE TITLE
remark@next (13)

### ISSUE THREAD

**Issue by wooorm** [sergioramos/remark-copy-linked-files#18]
Hi!

remark is switching to a new parser internally ([micromark](https://github.com/micromark/micromark), see [`remarkjs/remark#536`](https://github.com/remarkjs/remark/pull/536) for more info).
From a quick glance at the code, it seems this plugin should be fine. However, it would be good to check that in the future (there is `13.0.0-alpha.0` published now, and one or two more will come before the release)

**Comment by sergioramos** [comment]
thank you for the tip, appreciated @wooorm

**Comment by sergioramos** [comment]
Updated remark to v13 and tests are passing so I assume it is working with no change :) 

https://github.com/sergioramos/remark-copy-linked-files/commit/de3d25bb734e08cd7677ccc4e5551a154006f7e3

Thank you, again 👍
