### ISSUE TITLE
mz should be a dependency, not a devDependency

### ISSUE THREAD

**Issue by danoc** [sergioramos/remark-copy-linked-files#36]
Hello!

Thanks for this great plugin.

When I try to use it, Node complains that it can't find `mz`. I've confirmed that it doesn't get installed. I imagine this is because `mz` is currently a devDependency, not a dependency.

As a workaround, I've installed `mz` with `yarn add mz` but I'd love it it was included with this package.

Thanks!

**Comment by sergioramos** [comment]
thank you for noticing that @danoc
