### ISSUE TITLE
Basic Reproduction 

### ISSUE THREAD

**Issue by spences10** [sergioramos/remark-copy-linked-files#42]
Hi, is there any chance there could be either a basic usage example or clearer instructions on how to use this please?

Thanks

**Comment by sergioramos** [comment]
There is an usage example in (https://github.com/sergioramos/remark-copy-linked-files#usage) and you can also take a look at the tests (https://github.com/sergioramos/remark-copy-linked-files/blob/cef4a5f2c1ebca355169a71d466e75addce9c0ba/test/index.js#L91-L129)
