### ISSUE TITLE
Custom selectors

### ISSUE THREAD

**Issue by browniefed** [sergioramos/remark-copy-linked-files#43]
Would be great to add the ability to add custom selectors for cheerio.

**Comment by sergioramos** [comment]
would this solve that? https://github.com/sergioramos/remark-copy-linked-files/pull/46

**Comment by browniefed** [comment]
Yep I believe so. Just want to define custom paths for selecting JSX element props

**Comment by sergioramos** [comment]
Do you mind trying that change in your use-case? Or showing me a sample so that I can write an appropriate test case

**Comment by browniefed** [comment]
The MDX Document would be something along the lines of 

```
<MP4 src="./video.mp4" />
```

So I assume the selector would be along the lines of `['MP4[src]', 'src'],`

**Comment by sergioramos** [comment]
closed with https://github.com/sergioramos/remark-copy-linked-files/commit/91300a494de91b999887338355abae20ea2e1bbb

**Comment by browniefed** [comment]
Hmm doesn't seem like utilizing the custom selectors is copying the source video over.

With config

```
 customSelectors: [["MP4[src]", "src"]],
```

As the test
```
export const meta = {
  title: "Hello World!",
};

# Hello, world!

Lorem ipsum dolor sit amet.

![](./test.png)

<MP4 src="./video.mp4" />

```


<img width="404" alt="Screen Shot 2020-11-21 at 3 54 08 PM" src="https://user-images.githubusercontent.com/1714673/99890216-cff5f100-2c11-11eb-87f4-c876a19df4c4.png">

**Comment by sergioramos** [comment]
humm, need to check, thanks for letting me know.

**Comment by browniefed** [comment]
Apologies this was my bad. I read the code and saw `customSelectors` however the configuration to pass in is `selectors`.

This works great. Sorry for the confusion

**Comment by sergioramos** [comment]
no worries, glad it's working 😉
