### ISSUE TITLE
How do you use this in a Next.JS project?

### ISSUE THREAD

**Issue by spences10** [sergioramos/remark-copy-linked-files#47]
Hi,

Me again, you closed the last issue (#42) by pointing to code that I couldn't understand how to use(, this is why I opened the issues in the first place). Pointing to four lines of code doesn't really give usage instructions.

👇
```js
const destinationDir = __dirname;

remark()
  .use(require('remark-copy-linked-files'), { destinationDir })
  .use(require('remark-html'))
  .process(VFile({ path, contents }));
```
👆 in what context do I use this? 🤷‍♀️ I'll just chuck it in a random `.js` file somewhere and hope it works shall I? 😂

I've looked on GitHub and can't find any other projects using this, so I have nothing to go on how to use it.

My use case is for documentation in Next.JS with MDX, it looks like the test you're pointing to is for node and doesn't give me any more of an idea of how to use it in a Next.JS project.

It's open source so I was hoping that you'd be keen for other people to use this in their projects.

I'd be keen to share with other people how I've got linked images in Next.JS working with a detailed explanation for my use case, I'd be happy to contribute that here too.

**Comment by browniefed** [comment]
Here is an example that I use with `next.config.js`


```
const copyLinkedFiles = require("remark-copy-linked-files");
const path = require("path");
const PATH_NAE = "tutorial_files";
const destinationDir = path.join(__dirname, "public", PATH_NAE);

const withMDX = require("@next/mdx")({
  extension: /\.mdx?$/,
  options: {
    remarkPlugins: [
      [copyLinkedFiles, { destinationDir, staticPath: `/${PATH_NAE}` }],
    ],
  },
});

module.exports = withMDX({
  pageExtensions: ["ts", "tsx", "mdx"],
  webpack: (config, { isServer }) => {
    if (!isServer) {
      config.node = {
        fs: "empty",
      };
    }

    return config;
  },
});

```

Then I add `public/tutorial_files` to my `.gitignore`.

**Comment by spences10** [comment]
> Here is an example that I use with `next.config.js`

Fantastic! Thanks @browniefed 🙏

**Comment by sergioramos** [comment]
thank you @browniefed for the instructions 👍 

@spences10 the reason why I closed that issue is that you didn't even specify that you needed instructions to use with next.js. But with next.js it works like every other remark plugin.
